name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install requirements and their dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run builds
        run: python build.py build

      - name: Package binaries
        uses: vimtor/action-zip@v1.2
        with:
          files: build/exe.win-amd64-3.10/
          dest: SomaticVR-Eros-Flasher.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: SomaticVR-Eros-Flasher.zip

