name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install esptool and cx freeze and their dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_freeze esptool

      - name: Run builds
        run: python python build.py build

      - name: Package binaries
        run: zip dist/* dist/SomaticVR-Eros-Flasher.zip

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ./dist/*.zip

