name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install pio and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_freeze esptool

      - name: Run builds
        run: python -m cx-freeze .\FlashUtility.py --target-dir dist

      - name: Package build
        run: zip dist/* dist/SomaticVR-Eros-Flasher.zip

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ./dist/*.zip

